name: Python tests on windows

env:
  COLUMNS: 120

on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: echo some variables
        run: |
          echo [Environment]::GetEnvironmentVariable("PATH", "Machine")
          echo [IO.Path]::PathSeparator
          echo $IsWindows
          echo $PROFILE
          echo $PSHome
          echo $PWD

      - name: Run unit tests
        run: py.test analyzer/windows
