name: Python tests on windows

env:
  COLUMNS: 120

on:
  push:
    branches: [ master, staging ]
  pull_request:
    branches: [ master, staging ]

jobs:
  test:
    runs-on: windows-latest
    timeout-minutes: 20
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: echo some variables
        run: |
          echo $Env:Path.Split(';')

      - name: Install pytest
        run: pip install pytest

      - name: Run unit tests
        run: pytest analyzer/windows
